"""Python ``.pyi`` stub emitter.

Emits one stub per featureset and per dataset, plus an ``__init__.pyi`` that
re-exports the row classes. Every file is self-contained (no cross-file stub
imports beyond the ``__init__`` re-exports) so users can point their type
checker at the output directory without additional wiring.
"""

from __future__ import annotations

import re
from pathlib import Path

from thyme.codegen.ir import CodegenIR, DatasetIR, FeatureIR, FeaturesetIR
from thyme.codegen.types import annotation_requires_datetime_import


_SNAKE_RE_1 = re.compile(r"(.)([A-Z][a-z]+)")
_SNAKE_RE_2 = re.compile(r"([a-z0-9])([A-Z])")


def _snake_case(name: str) -> str:
    step1 = _SNAKE_RE_1.sub(r"\1_\2", name)
    return _SNAKE_RE_2.sub(r"\1_\2", step1).lower()


def _field_annotation(f: FeatureIR) -> str:
    return f"{f.python_annotation} | None" if f.optional else f.python_annotation


def _any_datetime(fields: tuple[FeatureIR, ...]) -> bool:
    return any(annotation_requires_datetime_import(f.python_annotation) for f in fields)


def _render_row_class(name: str, fields: tuple[FeatureIR, ...]) -> str:
    if not fields:
        return f"class {name}: ...\n"
    body = "\n".join(f"    {f.name}: {_field_annotation(f)}" for f in fields)
    return f"class {name}:\n{body}\n"


def _render_featureset_stub(fs: FeaturesetIR) -> str:
    lines: list[str] = [
        "# AUTO-GENERATED by `thyme codegen python` — do not edit by hand.",
        f"# Source featureset: {fs.name}",
        "from __future__ import annotations",
        "",
    ]
    if _any_datetime(fs.features):
        lines.append("import datetime")
    lines += [
        "from typing import overload",
        "",
        "import polars as pl",
        "",
        "from thyme.result import ThymeResult",
        "",
        _render_row_class(fs.name, fs.features),
        "",
        "class ThymeClient:",
        "    @overload",
        f"    def query(self, featureset: type[{fs.name}], entity_id: str) -> ThymeResult[{fs.name}]: ...",
        "    @overload",
        f"    def query_batch(self, featureset: type[{fs.name}], entity_ids: list[str]) -> ThymeResult[{fs.name}]: ...",
        "    @overload",
        "    def query_offline(",
        "        self,",
        f"        featureset: type[{fs.name}],",
        "        entities: pl.DataFrame | list[dict[str, object]] | object,",
        "        *,",
        "        entity_column: str,",
        "        timestamp_column: str,",
        "        batch_size: int = ...,",
        f"    ) -> ThymeResult[{fs.name}]: ...",
        "",
        "class MockContext:",
        "    @overload",
        f"    def query(self, featureset_class: type[{fs.name}], entity_id: str) -> dict[str, object]: ...",
        "    @overload",
        "    def query_offline(",
        "        self,",
        f"        featureset_class: type[{fs.name}],",
        "        entities: list[dict[str, object]],",
        "        *,",
        "        entity_column: str = ...,",
        "        timestamp_column: str = ...,",
        f"    ) -> ThymeResult[{fs.name}]: ...",
        "",
    ]
    return "\n".join(lines)


def _render_dataset_stub(ds: DatasetIR) -> str:
    lines: list[str] = [
        "# AUTO-GENERATED by `thyme codegen python` — do not edit by hand.",
        f"# Source dataset: {ds.name}",
        "from __future__ import annotations",
        "",
    ]
    if _any_datetime(ds.fields):
        lines.append("import datetime")
    lines += [
        "from typing import overload",
        "",
        "from thyme.result import ThymeResult",
        "",
        _render_row_class(ds.name, ds.fields),
        "",
        "class ThymeClient:",
        "    @overload",
        f"    def lookup(self, dataset: type[{ds.name}], entity_id: str, *, timestamp: str | None = ...) -> ThymeResult[{ds.name}]: ...",
        "",
    ]
    return "\n".join(lines)


def _render_init_stub(
    featuresets: tuple[FeaturesetIR, ...], datasets: tuple[DatasetIR, ...]
) -> str:
    lines = [
        "# AUTO-GENERATED by `thyme codegen python` — do not edit by hand.",
        "",
    ]
    for fs in featuresets:
        mod = _snake_case(fs.name)
        lines.append(f"from .{mod} import {fs.name} as {fs.name}")
    for ds in datasets:
        mod = _snake_case(ds.name)
        lines.append(f"from .{mod} import {ds.name} as {ds.name}")
    lines.append("")
    return "\n".join(lines)


def emit_python_stubs(
    ir: CodegenIR,
    out_dir: Path,
    force: bool = False,
) -> list[Path]:
    """Emit ``.pyi`` stubs for every featureset and dataset in ``ir``.

    One file per featureset / dataset plus an ``__init__.pyi`` re-exporting
    each class. Output is deterministic (IR is sorted by name).

    Args:
        ir: The codegen intermediate representation. Build via
            :func:`thyme.codegen.ir.build_ir`.
        out_dir: Directory to write stubs into. Created if missing.
        force: If True, remove any pre-existing ``*.pyi`` files in
            ``out_dir`` that aren't written this pass (stale-stub pruning).

    Returns:
        The list of paths written, in emission order.

    Raises:
        FileExistsError: If ``out_dir`` contains existing files and
            ``force`` is False.
    """
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    existing = [p for p in out_dir.iterdir() if p.is_file()]
    if existing and not force:
        raise FileExistsError(
            f"Output directory {out_dir} is not empty. "
            f"Pass --force to overwrite (will also prune stale *.pyi files)."
        )

    written: list[Path] = []
    for fs in ir.featuresets:
        path = out_dir / f"{_snake_case(fs.name)}.pyi"
        path.write_text(_render_featureset_stub(fs))
        written.append(path)

    for ds in ir.datasets:
        path = out_dir / f"{_snake_case(ds.name)}.pyi"
        path.write_text(_render_dataset_stub(ds))
        written.append(path)

    init_path = out_dir / "__init__.pyi"
    init_path.write_text(_render_init_stub(ir.featuresets, ir.datasets))
    written.append(init_path)

    if force:
        written_set = set(written)
        for path in out_dir.iterdir():
            if path.is_file() and path.suffix == ".pyi" and path not in written_set:
                path.unlink()

    return written
